BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task.yaml
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
NUM_PROCESSES: 1
VIDEO_OPTION: ["disk", "tensorboard"]
VIDEO_DIR: "video_dir"
TENSORBOARD_DIR: data/tensorboard_dirs/seq2seq2
CHECKPOINT_FOLDER: data/checkpoints/seq2seq2
EVAL_CKPT_PATH_DIR: data/checkpoints/seq2seq2

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: 50000

DAGGER:
  ITERATIONS: 10000
  EPOCHS: 2
  UPDATE_SIZE: 1
  BATCH_SIZE: 5
  P: 1.0
  PRELOAD_LMDB_FEATURES: False
  LMDB_FEATURES_DIR: data/trajectories_dirs/seq2seq2/trajectories.lmdb

MODEL:
  seq2seq2:
    use: True